#!/usr/bin/env bash
#
# Transplant phpBB table data from the upgraded local MariaDB 3.3.17 database
# into the canonical PostgreSQL 17 schema generated by create_pg_schema.sh.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MARIADB_CONTAINER="mariadb"
POSTGRES_CONTAINER="postgres"
WORK_DIR="data/migration/db-transplant"

set -a
# shellcheck disable=SC1091
. ./.env
set +a
DB_NAME="${DB_NAME:-lithharbor}"
DB_USER="${DB_USER:-lithharbor}"
DB_PASSWORD="${DB_PASSWORD:-dev}"

pg_query() {
  docker exec -e PGPASSWORD="$DB_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -U "$DB_USER" -d "$DB_NAME" -At -v ON_ERROR_STOP=1 -c "$1"
}

mysql_query() {
  docker exec -e MYSQL_PWD="$MARIADB_ROOT_PASSWORD" "$MARIADB_CONTAINER" \
    mariadb -uroot -N -B "$DB_NAME" -e "$1"
}

pg_ident_list() {
  local table="$1"
  mysql_query "SELECT column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='$table' ORDER BY ordinal_position;" |
    sed 's/"/""/g; s/.*/"&"/' |
    paste -sd, -
}

map_mysql_type_to_pg() {
  local mysql_type="$1"
  case "$mysql_type" in
    varchar\(*\)) printf '%s' "$mysql_type" ;;
    *text*) printf 'text' ;;
    tinyint*|smallint*) printf 'smallint' ;;
    mediumint*|int*) printf 'integer' ;;
    bigint*) printf 'bigint' ;;
    *) echo "ERROR: unsupported custom profile field type $mysql_type" >&2; return 1 ;;
  esac
}

mapfile -t TABLES < <(pg_query "SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name LIKE 'phpbb\\_%' ESCAPE '\\' ORDER BY table_name;")
if [ "${#TABLES[@]}" -eq 0 ]; then
  echo "ERROR: PostgreSQL has no phpbb_ tables. Run scripts/create_pg_schema.sh first." >&2
  exit 1
fi

echo ">> Checking every canonical phpBB table exists in MariaDB"
for table in "${TABLES[@]}"; do
  exists="$(mysql_query "SHOW TABLES LIKE '$table';")"
  if [ "$exists" != "$table" ]; then
    echo "ERROR: MariaDB is missing canonical table $table" >&2
    exit 1
  fi
done

echo ">> Preserving source columns absent from the clean PostgreSQL install"
for table in "${TABLES[@]}"; do
  while IFS=$'\t' read -r column column_type _is_nullable; do
    [ -n "$column" ] || continue
    exists="$(pg_query "SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='$table' AND column_name='$column';")"
    if [ -z "$exists" ]; then
      pg_type="$(map_mysql_type_to_pg "$column_type")"
      pg_query "ALTER TABLE \"$table\" ADD COLUMN \"$column\" $pg_type NULL;"
      echo "OK:   added $table.$column ($pg_type)"
    fi
  done < <(mysql_query "SELECT column_name, column_type, is_nullable FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='$table' ORDER BY ordinal_position;")
done

echo ">> Exporting MariaDB table data as text"
docker exec "$MARIADB_CONTAINER" rm -rf /tmp/db-transplant
docker exec "$MARIADB_CONTAINER" mkdir -p /tmp/db-transplant
docker exec "$MARIADB_CONTAINER" chmod 0777 /tmp/db-transplant
docker exec -e MYSQL_PWD="$MARIADB_ROOT_PASSWORD" "$MARIADB_CONTAINER" \
  mariadb-dump -uroot "$DB_NAME" "${TABLES[@]}" \
  --tab=/tmp/db-transplant \
  --no-create-info \
  --fields-terminated-by=$'\t' \
  --fields-enclosed-by='"' \
  --fields-escaped-by='\\' \
  --lines-terminated-by=$'\n'

rm -rf "$WORK_DIR"
mkdir -p "$(dirname "$WORK_DIR")"
docker cp "$MARIADB_CONTAINER:/tmp/db-transplant" "$WORK_DIR"
perl -0pi -e 's/\\\n/\n/g' "$WORK_DIR"/*.txt

quoted_tables="$(printf '"%s",' "${TABLES[@]}")"
quoted_tables="${quoted_tables%,}"
echo ">> Truncating PostgreSQL canonical tables"
pg_query "TRUNCATE $quoted_tables;"

echo ">> Loading text data into PostgreSQL"
for table in "${TABLES[@]}"; do
  docker cp "$WORK_DIR/$table.txt" "$POSTGRES_CONTAINER:/tmp/$table.txt"
  columns="$(pg_ident_list "$table")"
  docker exec -e PGPASSWORD="$DB_PASSWORD" "$POSTGRES_CONTAINER" \
    psql -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1 \
    -c "\\copy \"$table\" ($columns) FROM '/tmp/$table.txt' WITH (FORMAT csv, DELIMITER E'\t', NULL '\N', QUOTE '\"', ESCAPE E'\\\\')"
done

echo ">> Resetting PostgreSQL sequences to max(id)+1"
docker exec -e PGPASSWORD="$DB_PASSWORD" "$POSTGRES_CONTAINER" \
  psql -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1 <<'SQL'
SELECT format(
  'SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, false);',
  seq.relname,
  col.attname,
  tbl.relname
)
FROM pg_class seq
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_attribute col ON col.attrelid = tbl.oid AND col.attnum = dep.refobjsubid
JOIN pg_namespace ns ON ns.oid = seq.relnamespace
WHERE seq.relkind = 'S' AND ns.nspname = 'public'
ORDER BY tbl.relname, col.attname
\gexec
SQL

echo ">> Verifying transplant parity"
scripts/db_transplant.py verify
